/*
 * ineedmd_system_monitoring.c
 *
 *  Created on: Nov 18, 2014
 *      Author: BrianS
 */
#ifndef __INEEDMD_SYSTEM_MONITORING_C__
#define __INEEDMD_SYSTEM_MONITORING_C__
/******************************************************************************
* Includes
******************************************************************************/

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "inc/hw_sysctl.h"
#include "driverlib/adc.h"
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
//#include "driverlib/i2c.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/ssi.h"
#include "driverlib/sysctl.h"
#include "driverlib/uart.h"
#include "driverlib/usb.h"
#include "driverlib/timer.h"
#include "driverlib/interrupt.h"

#include "utils_inc/error_codes.h"

#include "drivers_inc/ineedmd_adc.h"
#include "inc/tm4c1233h6pm.h"
#include "board.h"
#include "utils_inc/proj_debug.h"

/*********************************************************************
 *
 * Defines
 *
 *********************************************************************/
#define ARRAY_OF_MEASUREMENTS 16

/*********************************************************************
 *
 * Structures
 *
 *********************************************************************/

struct sMeasurement_Data
{
  uint8_t array_position;
  uint32_t measuremet[ARRAY_OF_MEASUREMENTS];
  uint32_t average_measurement;
};

/*********************************************************************
 *
 * Variables
 *
 *********************************************************************/

static struct sMeasurement_Data temperature_data;
static struct sMeasurement_Data voltage_data;


/*********************************************************************
 *
 * function_def
 *
 *********************************************************************/

void ineedmd_crash_and_burn( ERROR_CODE eEC);
extern uint32_t ineedmd_temperature(void);
extern uint32_t ineedmd_voltage(void);
ERROR_CODE ineedmd_init_temperature_adc(void);
ERROR_CODE ineedmd_init_voltage_adc(void);
ERROR_CODE ineedmd_measure_temperature_adc(void);
ERROR_CODE ineedmd_measure_voltage_adc(void);
ERROR_CODE ineedmd_initial_condition_temperature_adc(void);
ERROR_CODE ineedmd_initial_condition_voltage_adc(void);
void ineedmd_average_temperature_adc(void);
void ineedmd_average_voltage_adc(void);
extern void vIineedmd_system_measurement();


/*********************************************************************
 *
 * Code Beyond here
 *
 *********************************************************************/

void
ineedmd_crash_and_burn (ERROR_CODE eEC)
{

  //todo is the is correct hell and damnation
  while (1)
  {

  }
}


/*********************************************************************
 *
 * External call to get the temperature... it is passed in dC
 *
 *********************************************************************/
uint32_t
ineedmd_temperature()
{
  uint8_t temperature_is = 0;

  temperature_is = 1475 - ((2250 * temperature_data.average_measurement) / 4095);

  return temperature_is;
}

/*********************************************************************
 *
 * External call to get the battery voltage... it is passed in mV above 2.5V
 *
 *********************************************************************/
uint32_t
ineedmd_voltage()
{
  uint8_t voltage_is = 0;

  voltage_is = ( ( ( voltage_data.average_measurement * 161 ) - 250000 ) / 10000 );

  return voltage_is;
}

/*********************************************************************
 *
 * Initalise the ADC for the temperature monitor
 *
 *********************************************************************/
ERROR_CODE
ineedmd_init_temperature_adc()
{
  ERROR_CODE  eEC = ER_OK;
  //switch off the sequencer so the configuration can be made
  ADCSequenceDisable(BATTERY_ADC, 3);
  //set the ADC reference to internal 3V
  ADCReferenceSet(BATTERY_ADC, ADC_REF_INT);
  //set the ADC to be triggered by the processor asking for a conversion not a timer.  This reduces reduces interupts
  //at the expence of some processor cycles  The interupt will only be used in the ADC block so doesn't need to be registered
  ADCSequenceConfigure(BATTERY_ADC, 3, ADC_TRIGGER_PROCESSOR, 0);
  //set the source to ..
  //    ADC_CTL_TS- Temperature channel
  //    ADC_CTL_IE - generate an interupt wen complete .. needed for the wait function
  //    ADC_CTL_END - This is the last step in the process.
  ADCSequenceStepConfigure(BATTERY_ADC, 3, 0, ADC_CTL_CH3 | ADC_CTL_IE | ADC_CTL_END );
  //clear the interupt generated by the configureation
  ADCIntClear(BATTERY_ADC, 3);
  // enable the sequencer for action
  ADCSequenceEnable(BATTERY_ADC, 3);

  return eEC;
}

/*********************************************************************
 *
 * Initalise the ADC for the voltage monitor
 *
 *********************************************************************/
ERROR_CODE
ineedmd_init_voltage_adc()
{
  ERROR_CODE  eEC = ER_OK;
  //switch off the sequencer so the configuration can be made
  ADCSequenceDisable(TEMPERATURE_ADC, 3);
  //set the ADC reference to internal 3V
  ADCReferenceSet(TEMPERATURE_ADC, ADC_REF_INT);
  //set the ADC to be triggered by the processor asking for a conversion not a timer.  This reduces reduces interupts
  //at the expence of some processor cycles  The interupt will only be used in the ADC block so doesn't need to be registered
  ADCSequenceConfigure(TEMPERATURE_ADC, 3, ADC_TRIGGER_PROCESSOR, 0);
  //set the source to ..
  //    ADC_CTL_TS- Temperature channel
  //    ADC_CTL_IE - generate an interupt wen complete .. needed for the wait function
  //    ADC_CTL_END - This is the last step in the process.
  ADCSequenceStepConfigure(TEMPERATURE_ADC, 3, 0, ADC_CTL_TS | ADC_CTL_IE | ADC_CTL_END );
  //clear the interupt generated by the configureation
  ADCIntClear(TEMPERATURE_ADC, 3);
  // enable the sequencer for action
  ADCSequenceEnable(TEMPERATURE_ADC, 3);


  return eEC;
}
/*********************************************************************
 *
 * Measures the ADC for the temperature monitor
 *
 *********************************************************************/
ERROR_CODE
ineedmd_measure_temperature_adc()
{
  ERROR_CODE  eEC = ER_OK;

  // ask for a conversion
  ADCProcessorTrigger(TEMPERATURE_ADC,3);
  //wait for it to be done
  while(!ADCIntStatus(TEMPERATURE_ADC, 3, false))
  {
    // seed to the rest of the system
    Task_Sleep(10);
  }
  //tidy awa the interupt...
  ADCIntClear(TEMPERATURE_ADC, 3);
  //finally get the data
  ADCSequenceDataGet(TEMPERATURE_ADC, 3, &temperature_data.measuremet[temperature_data.array_position]);
  //if there is a 0 then something fed uped.
  if (temperature_data.measuremet[temperature_data.array_position]==0)
  {
    eEC = ER_FAIL;
  }
  return eEC;
}

/*********************************************************************
 *
 * Measures the ADC for the voltage monitor
 *
 *********************************************************************/
ERROR_CODE
ineedmd_measure_voltage_adc()
{
  ERROR_CODE  eEC = ER_OK;

  // ask for a conversion
  ADCProcessorTrigger(BATTERY_ADC,3);
  //wait for it to be done
  while(!ADCIntStatus(BATTERY_ADC, 3, false))
  {
    // seed to the rest of the system
    Task_Sleep(10);
  }
  //tidy awa the interupt...
  ADCIntClear(BATTERY_ADC, 3);
  //finally get the data
  ADCSequenceDataGet(BATTERY_ADC, 3, &voltage_data.measuremet[voltage_data.array_position]);
  //if there is a 0 then something fed uped.
  if (voltage_data.measuremet[voltage_data.array_position]==0)
  {
    eEC = ER_FAIL;
  }
  return eEC;
}
/*********************************************************************
 *
 * Initalise the temperature storage array
 *
 *********************************************************************/
ERROR_CODE
ineedmd_initial_condition_temperature_adc()
{
  ERROR_CODE  eEC = ER_OK;
  temperature_data.array_position = 0;

  while (temperature_data.array_position < ARRAY_OF_MEASUREMENTS )
  {
    eEC = ineedmd_measure_temperature_adc();
    if (eEC != ER_OK)
    {
      break;
    }
    temperature_data.array_position++;
  }
  if (eEC == ER_OK)
  {
    temperature_data.array_position = 0;
  }
  return eEC;
}

/*********************************************************************
 *
 * Initalise the voltage storage array
 *
 *********************************************************************/
ERROR_CODE
ineedmd_initial_condition_voltage_adc()
{
  ERROR_CODE  eEC = ER_OK;
  voltage_data.array_position = 0;

  while (voltage_data.array_position < ARRAY_OF_MEASUREMENTS )
  {
    eEC = ineedmd_measure_voltage_adc();
    if (eEC != ER_OK)
    {
      break;
    }
    voltage_data.array_position++;
  }
  if (eEC == ER_OK)
  {
    voltage_data.array_position = 0;
  }
  return eEC;
}

/*********************************************************************
 *
 * Averages the readings so that when called there is always a valid set
 *
 *********************************************************************/
void
ineedmd_average_voltage_adc()
{
  uint8_t counter = 0;
  uint8_t summed_value = 0;

  for (counter; counter < ARRAY_OF_MEASUREMENTS; counter++ )
  {
    summed_value = summed_value + voltage_data.measuremet[counter];
  }
  voltage_data.average_measurement = summed_value /  ARRAY_OF_MEASUREMENTS;
}

/*********************************************************************
 *
 * Averages the readings so that when called there is always a valid set
 *
 *********************************************************************/
void
ineedmd_average_temperature_adc()
{
  uint8_t counter = 0;
  uint8_t summed_value = 0;

  for (counter; counter < ARRAY_OF_MEASUREMENTS; counter++ )
  {
    summed_value = summed_value + temperature_data.measuremet[counter];
  }
  temperature_data.average_measurement = summed_value /  ARRAY_OF_MEASUREMENTS;
}

/*********************************************************************
 *
 * System monitor task runns and sets up the ADCs and measures analog
 * parameters.    This low priority task sleeps for most of the time.
 *
 *********************************************************************/

void
vIineedmd_system_measurement ()
{

  ERROR_CODE  eEC = ER_OK;
  //sets up the temperatur monitoring ADC

  eEC = ineedmd_init_temperature_adc();
  if (eEC != ER_OK)
  {
    ineedmd_crash_and_burn(eEC);
  }
  //populates the averaging array for the temperature

  eEC = ineedmd_init_temperature_adc();
  if (eEC != ER_OK)
  {
    ineedmd_crash_and_burn(eEC);
  }
  //sets up the voltage monitoring ADC

  eEC = ineedmd_initial_condition_temperature_adc();
  if (eEC != ER_OK)
  {
    ineedmd_crash_and_burn(eEC);
  }
  ineedmd_average_temperature_adc();
  //populates the averaging array for the voltage

  eEC = ineedmd_initial_condition_temperature_adc();
  if (eEC != ER_OK)
  {
    ineedmd_crash_and_burn(eEC);
  }
  ineedmd_average_voltage_adc();

  while (1)
  {


    eEC = ineedmd_measure_voltage ();
    if (eEC != ER_OK)
    {
      ineedmd_crash_and_burn(eEC);
    }
    ineedmd_average_voltage_adc();


    eEC = ineedmd_measure_temperature ();
    if (eEC != ER_OK)
    {
      ineedmd_crash_and_burn(eEC);
    }
    ineedmd_average_temperature_adc();


    temperature_data.array_position++;
    voltage_data.array_position++;

    if ( temperature_data.array_position >= ARRAY_OF_MEASUREMENTS )
    {
      temperature_data.array_position = 0;
    }
    if ( voltage_data.array_position >= ARRAY_OF_MEASUREMENTS )
    {
      voltage_data.array_position = 0;
    }

    // task slleps then loops and takesanother measurement
    Task_sleep (60000);


  }

}


#endif // __INEEDMD_SYSTEM_MONITORING_C__

/*********************************************************************
 *
 * end of the world beyond here
 *
 *********************************************************************/
