//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#ifndef __BOARD_C__
#define __BOARD_C__
//*****************************************************************************
// includes
//*****************************************************************************
#include "file.h"
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "utils_inc/proj_debug.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_gpio.h"
#include "inc/hw_sysctl.h"
#include "inc/hw_uart.h"
#include "driverlib/adc.h"
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
#include "driverlib/i2c.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/ssi.h"
#include "driverlib/sysctl.h"
#include "driverlib/timer.h"
#include "driverlib/uart.h"
#include "driverlib/usb.h"
#include "driverlib/udma.h"

#include "inc/tm4c1233h6pm.h"
#include "board.h"


//*****************************************************************************
// defines
//*****************************************************************************
//radio uart DMA defines
#define USE_RADIO_UART_DMA      false
#define DMA_RDIO_RCV_BUFFSZ     1024
#define NUM_DMA_RDIO_RCV_BUFFS  3

#define DMA_RDIO_TX_BUFFSZ             256
#define NUM_DMA_RDIO_TX_BUFFS          3
#define RADIO_TX_UDMA_CHANNEL_BITMASK  0b00000000100000000000000000000000
#define RADIO_RX_UDMA_CHANNEL_BITMASK  0b00000000010000000000000000000000

/******************************************************************************
* variables
******************************************************************************/
volatile bool bIs_usart_data = false;
volatile bool bIs_uart_done = false;
volatile bool bIs_usart_timeout = false;
volatile bool bRdio_track_timeout_tick = false;
volatile uint32_t uiRdio_timeout_tick = 0;
volatile bool bIs_USB_sof = false;
volatile bool bWaveform_timer_tick = false;
static   bool bIs_Radio_UART_using_dma = false;
static   bool bIs_Radio_in_cmnd_mode = false;
volatile int  iNum_cmnd_buffs = 0;
volatile int  iNum_cts_procs = 0;
volatile bool bIs_DMA_transmit_in_process = false;
uint32_t uiSys_clock_rate_ms = 0;

//*****************************************************************************
// The control table used by the uDMA controller. This table must be aligned to a 1024 byte boundary.
//*****************************************************************************
#if defined(ewarm)
#pragma data_alignment=1024
uint8_t ui8ControlTable[1024];
#elif defined(ccs)
#pragma DATA_ALIGN(ui8ControlTable, 1024)
uint8_t ui8ControlTable[1024];
#else
uint8_t ui8ControlTable[1024] __attribute__ ((aligned(1024)));
#endif

//*****************************************************************************
// external variables
//*****************************************************************************

//*****************************************************************************
// enums
//*****************************************************************************
typedef enum
{
  RB_NONE,
  RB_IWRAP_CMND,
  RB_INEEDMD_CMND,
  RB_OTHER
}eRcv_Buff_type;

//*****************************************************************************
// structures
//*****************************************************************************
typedef struct
{
  bool bBuff_free;
  eRcv_Buff_type eApp_Buff_Dest;
  uint8_t uiRcv_Buff[DMA_RDIO_RCV_BUFFSZ];
  uint16_t uiRcv_data_len;
}tDMA_RX_struct;  //dma transmit data struct

typedef struct
{
  bool bBuff_free;
  uint8_t uiTx_Buff[DMA_RDIO_TX_BUFFSZ];
  uint16_t uiTx_data_len;
}tDMA_TX_struct;  //dma transmit data struct

#if USE_RADIO_UART_DMA == true
tDMA_RX_struct tDMA_RX_struct_array[NUM_DMA_RDIO_RCV_BUFFS];
tDMA_TX_struct tDMA_TX_struct_array[NUM_DMA_RDIO_TX_BUFFS];
#endif

//*****************************************************************************
// external functions
//*****************************************************************************

//*****************************************************************************
// private function declarations
//*****************************************************************************
ERROR_CODE Radio_UART_DMA_Config(void); //configures the DMA tied to the radio UART
void vRadio_interface_DMA_tx_service(void);
void vRadio_interface_DMA_rcv_service(void);
ERROR_CODE eGet_curr_DMA_fill_buff(tDMA_RX_struct ** ptDMA_curr_rx_buff);

//*****************************************************************************
// private functions
//*****************************************************************************
/******************************************************************************
* name: Radio_UART_DMA_Config
* description: configures the DMA for the radio uart
* param description:
* return value description:
******************************************************************************/
ERROR_CODE Radio_UART_DMA_Config(void)
{
  ERROR_CODE  eEC = ER_OK;
#if USE_RADIO_UART_DMA == true
  int i;
  bool bDMA_is_enabled = false;
  uint32_t  uiDMA_mode = 0;

  tDMA_RX_struct * ptFirst_DMA_RX_struct;

  //init the UART DMA rcv buffers
  for(i = 0; i < NUM_DMA_RDIO_RCV_BUFFS; i++)
  {
    tDMA_RX_struct_array[i].eApp_Buff_Dest = RB_NONE;
    tDMA_RX_struct_array[i].bBuff_free       = true;
    tDMA_RX_struct_array[i].uiRcv_data_len   = 0;
    memset(&tDMA_RX_struct_array[i].uiRcv_Buff, 0x00, DMA_RDIO_RCV_BUFFSZ);
  }

  //init the UART DMA tx buffers
  for(i = 0; i < NUM_DMA_RDIO_TX_BUFFS; i++)
  {
    tDMA_TX_struct_array[i].bBuff_free     = true;
    tDMA_TX_struct_array[i].uiTx_data_len  = 0;
    memset(&tDMA_TX_struct_array[i].uiTx_Buff, 0x00, DMA_RDIO_TX_BUFFSZ);
  }

  //keep track of the first buffer to use
  ptFirst_DMA_RX_struct = &tDMA_RX_struct_array[0];

  // Enable the uDMA controller at the system level.  Enable it to continue
  // to run while the processor is in sleep.
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UDMA);
  MAP_SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UDMA);

  // Enable the uDMA controller error interrupt.  This interrupt will occur
  // if there is a bus error during a transfer.
  MAP_IntEnable(INT_UDMAERR);

  // Enable the uDMA controller.
  MAP_uDMAEnable();

  // Point at the control table to use for channel control structures.
  MAP_uDMAControlBaseSet(ui8ControlTable);

  //
  // Set both the TX and RX trigger thresholds to 4.  This will be used by
  // the uDMA controller to signal when more data should be transferred.  The
  // uDMA TX and RX channels will be configured so that it can transfer 4
  // bytes in a burst when the UART is ready to transfer more data.
  //
//  MAP_UARTFIFOLevelSet(INEEDMD_RADIO_UART, UART_FIFO_TX4_8, UART_FIFO_RX4_8);
  MAP_UARTFIFOLevelSet(INEEDMD_RADIO_UART, UART_FIFO_TX1_8, UART_FIFO_RX1_8);

  // Enable the uDMA interface for both TX and RX channels.
  MAP_UARTDMAEnable(INEEDMD_RADIO_UART, UART_DMA_RX | UART_DMA_TX);

  // Enable the UART peripheral interrupts.  Note that no UART interrupts
  // were enabled, but the uDMA controller will cause an interrupt on the
  // UART interrupt signal when a uDMA transfer is complete.
  //
//  MAP_IntEnable(INEEDMD_RADIO_UART_INT);
//  MAP_UARTIntEnable(INEEDMD_RADIO_UART, UART_INT_RX | UART_INT_RT | UART_INT_CTS);
  iRadio_interface_int_enable();

  //
  //configure the Radio UART receive DMA
  //

  // Put the attributes in a known state for the uDMA RADIO UART RX channel.  These
  // should already be disabled by default.
  //
  MAP_uDMAChannelAttributeDisable(UDMA_CHANNEL_RADIO_RX,
                                  UDMA_ATTR_USEBURST |
                                  UDMA_ATTR_HIGH_PRIORITY |
                                  UDMA_ATTR_REQMASK);

  MAP_uDMAChannelAttributeEnable(UDMA_CHANNEL_RADIO_RX, UDMA_ATTR_HIGH_PRIORITY);

  // Configure the control parameters for the primary control structure for
  // the UART RX channel.  The transfer data size is 8 bits, the
  // source address does not increment since it will be reading from a
  // register.  The destination address increment is byte 8-bit bytes.  The
  // arbitration size is set to 4 to match the RX FIFO trigger threshold.
  // The uDMA controller will use a 4 byte burst transfer if possible.
  MAP_uDMAChannelControlSet(UDMA_CHANNEL_RADIO_RX | UDMA_PRI_SELECT,
                            UDMA_SIZE_8 | UDMA_SRC_INC_NONE | UDMA_DST_INC_8 |
                            UDMA_ARB_1);

  // Set up the transfer parameters for the UART RX primary control
  // structure.
  MAP_uDMAChannelTransferSet(UDMA_CHANNEL_RADIO_RX | UDMA_PRI_SELECT,
                             UDMA_MODE_BASIC,
                             (void *)(INEEDMD_RADIO_UART + UART_O_DR),
                             ptFirst_DMA_RX_struct->uiRcv_Buff, DMA_RDIO_RCV_BUFFSZ);

  ptFirst_DMA_RX_struct->bBuff_free = false;

  //Enable the Radio DMA UART receive channel
  MAP_uDMAChannelEnable(UDMA_CHANNEL_RADIO_RX);

  //
  //configure the Radio UART transmit DMA
  //

  // Put the attributes in a known state for the uDMA Radio UART TX channel.  These
  // should already be disabled by default.
  MAP_uDMAChannelAttributeDisable(UDMA_CHANNEL_RADIO_TX,
                                  UDMA_ATTR_HIGH_PRIORITY |
                                  UDMA_ATTR_REQMASK);

  // Set the USEBURST attribute for the uDMA UART TX channel.  This will
  // force the controller to always use a burst when transferring data from
  // the TX buffer to the UART.
//  MAP_uDMAChannelAttributeEnable(UDMA_CHANNEL_RADIO_TX, UDMA_ATTR_USEBURST);
  MAP_uDMAChannelAttributeEnable(UDMA_CHANNEL_RADIO_TX, UDMA_ATTR_HIGH_PRIORITY);

  // Configure the control parameters for the Radio UART TX.  The uDMA UART TX
  // channel is used to transfer a block of data from a buffer to the UART.
  // The data size is 8 bits.  The source address increment is 8-bit bytes
  // since the data is coming from a buffer.  The destination increment is
  // none since the data is to be written to the UART data register.  The
  // arbitration size is set to 4, which matches the UART TX FIFO trigger
  // threshold.
  MAP_uDMAChannelControlSet(UDMA_CHANNEL_RADIO_TX | UDMA_PRI_SELECT,
                            UDMA_SIZE_8 | UDMA_SRC_INC_8 | UDMA_DST_INC_NONE |
                            UDMA_ARB_1);

  //Enable the Radio DMA UART transmit channel
  //todo: not needed?
//  MAP_uDMAChannelEnable(UDMA_CHANNEL_RADIO_TX);

  //Performing setup checks

  //check if the DMA's are enabled
  if(eEC == ER_OK)
  {
    //check if RX DMA is enabled
    bDMA_is_enabled = MAP_uDMAChannelIsEnabled(UDMA_CHANNEL_RADIO_RX);
    if(bDMA_is_enabled == false)
    {
      eEC = ER_NOT_ENABLED;
    }
    else
    {
      //todo: this check may not be needed since we have nothing to send yet
//      //check if the TX DMA is enabled
//      bDMA_is_enabled = MAP_uDMAChannelIsEnabled(UDMA_CHANNEL_RADIO_TX);
//      if(bDMA_is_enabled == false)
//      {
//        eEC = ER_NOT_ENABLED;
//      }
//      else
//      {
        eEC = ER_OK;
//      }
    }
  }

  //check the DMA's mode
  if(eEC == ER_OK)
  {
    //check RX DMA mode
    uiDMA_mode = ROM_uDMAChannelModeGet((UDMA_CHANNEL_RADIO_RX | UDMA_PRI_SELECT));
    if((uiDMA_mode && UDMA_MODE_BASIC) != UDMA_MODE_BASIC)
    {
      eEC = ER_MODE;
    }
    else
    {
      //todo: this check may not be needed since we have nothing to send yet
//      //check if the TX DMA mode
//      uiDMA_mode = ROM_uDMAChannelModeGet((UDMA_CHANNEL_RADIO_TX | UDMA_PRI_SELECT));
//      if((uiDMA_mode && UDMA_MODE_BASIC) != UDMA_MODE_BASIC)
//      {
//        eEC = ER_MODE;
//      }
//      else
//      {
        eEC = ER_OK;
//      }
    }
  }

  if(eEC == ER_OK)
  {
    //set the UART using dma control variable
    bIs_Radio_UART_using_dma = true;
  }
#elif  USE_RADIO_UART_DMA == false
  eEC = ER_NOT_ENABLED;
#endif //USE_RADIO_UART_DMA
  return eEC;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vRadio_interface_DMA_tx_service(void)
{
  int index;
#if USE_RADIO_UART_DMA == true
  tDMA_TX_struct * ptDMA_tx_buff = NULL;

  //cycle through the buffers and find the one that was transmitted
  for(index = 0; index < NUM_DMA_RDIO_TX_BUFFS; index++)
  {
    ptDMA_tx_buff = &tDMA_TX_struct_array[index];

    //check if the buffer is NOT free, therefore filled for TX
    if(ptDMA_tx_buff->bBuff_free == false)
    {
      ptDMA_tx_buff->bBuff_free = true;
      memset(ptDMA_tx_buff->uiTx_Buff, 0x00, DMA_RDIO_TX_BUFFSZ);
    }else{/*nothing*/}
  }
#endif
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vRadio_interface_DMA_rcv_service(void)
{
#define DEBUG_vRadio_interface_DMA_rcv_service
#ifdef DEBUG_vRadio_interface_DMA_rcv_service
  #define  vDEBUG_DMA_RCV_SRVC  vDEBUG
#else
  #define vDEBUG_DMA_RCV_SRVC(a)
#endif
  ERROR_CODE eEC = ER_FAIL;
#if USE_RADIO_UART_DMA == true
  int index;
  tDMA_RX_struct * ptDMA_que_buff = NULL;

  //cycle through the buffers and find the one that was filled
  for(index = 0; index < NUM_DMA_RDIO_RCV_BUFFS; index++)
  {
    ptDMA_que_buff = &tDMA_RX_struct_array[index];

    //check if the buffer is NOT free, therefore potentially was filled via DMA
    if(ptDMA_que_buff->bBuff_free == false)
    {
      //check if the buffer was NOT already queued for an app to review
      if(ptDMA_que_buff->eApp_Buff_Dest == RB_NONE)
      {
        eEC = eIs_radio_in_cmnd_mode();
        if(eEC == ER_TRUE)
        {
          ptDMA_que_buff->eApp_Buff_Dest = RB_IWRAP_CMND;
          eEC = ER_OK;
          continue;
        }
        else
        {
          eEC = ER_OK;
        }

        if(ptDMA_que_buff->uiRcv_Buff[0] == 0x9C)
        {
          ptDMA_que_buff->eApp_Buff_Dest = RB_INEEDMD_CMND;
          continue;
        }
      }else{/*nothing*/}
    }else{/*nothing*/}
  }

  //check the error code to determine if none of the buffers were serviced
  if(eEC == ER_FAIL)
  {
    //There is no data to send to the application
    eEC = ER_NODATA;
  }else{/*nothing*/}

  //check the error status and proceed accordingly
  if(eEC == ER_OK)
  {
//    MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_RX);

    //preset the error code
    eEC = ER_FAIL;

    //cycle the buffers and fine a free one to assign to the DMA
    for(index = 0; index < NUM_DMA_RDIO_RCV_BUFFS; index++)
    {
      ptDMA_que_buff = &tDMA_RX_struct_array[index];

      //check if the buffer is free to fill via DMA
      if(ptDMA_que_buff->bBuff_free == true)
      {
        //check if the buffer was NOT already queued for an app to review
        if(ptDMA_que_buff->eApp_Buff_Dest == RB_NONE)
        {
          //set the DMA RX to the next rcv buffer
          ROM_uDMAChannelTransferSet(UDMA_CHANNEL_UART1RX | UDMA_PRI_SELECT,
                                     UDMA_MODE_BASIC,
                                     (void *)(INEEDMD_RADIO_UART + UART_O_DR),
                                     ptDMA_que_buff->uiRcv_Buff, DMA_RDIO_RCV_BUFFSZ);

          //mark the buffer as in use
          ptDMA_que_buff->bBuff_free = false;
          MAP_uDMAChannelEnable(UDMA_CHANNEL_RADIO_RX);
          eEC = ER_OK;
          break;

        }else{/*nothing*/}
      }else{/*nothing*/}
    }
  }else{/*nothing*/}

  //check if a free buffer was not allocated
  if(eEC == ER_FAIL)
  {
    eEC = ER_NO_BUFF_AVAILABLE;
  }else{/*nothing*/}


  //check for errors
  if(eEC == ER_NO_BUFF_AVAILABLE)
  {
#ifdef DEBUG
    // Catch no buffers available
    vDEBUG_DMA_RCV_SRVC("Dma rcv srvc SYS HALT, no buff available");
    while(1){};
#else
    //todo: perform a system reset maybe?
#endif
  }
  else if(eEC == ER_NODATA)
  {
    //todo: need a nodata counter maybe?
#ifdef DEBUG
    // Catch no data available
    vDEBUG_DMA_RCV_SRVC("Dma rcv srvc SYS HALT, no data available");
    while(1){};
#else
    //todo: need a nodata counter maybe?
#endif
  }
  else{/*nothing*/}
#endif //USE_RADIO_UART_DMA
  return;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eGet_curr_DMA_fill_buff(tDMA_RX_struct ** ptDMA_curr_rx_buff)
{
  ERROR_CODE eEC = ER_FAIL;
#if USE_RADIO_UART_DMA == true
  int index = 0;
  tDMA_RX_struct * ptDMA_rx_buff = NULL;

  //cycle through the buffers and find the one that was filled
  for(index = 0; index < NUM_DMA_RDIO_RCV_BUFFS; index++)
  {
    ptDMA_rx_buff = &tDMA_RX_struct_array[index];

    //check if the buffer is NOT free, therefore potentially was filled via DMA
    if(ptDMA_rx_buff->bBuff_free == false)
    {
      //check if the buffer was NOT already queued for an app to review
      if(ptDMA_rx_buff->eApp_Buff_Dest == RB_NONE)
      {
        *ptDMA_curr_rx_buff = ptDMA_rx_buff;
        eEC = ER_OK;
      }else{/*nothing*/}
    }else{/*nothing*/}
  }
#endif
  return eEC;
}
//*****************************************************************************

// external functions
//*****************************************************************************
//
//a processor loop wait timer.  The number of cycles are calculated from the frequency of the main clock.
//
void wait_time (unsigned int tenths_of_seconds)
{
	MAP_SysCtlDelay(( MAP_SysCtlClockGet() / 30  )*tenths_of_seconds );
}


//
//a 2 BYTE i2C WRITE ROUTINE.  No error checking is implemented
//
void write_2_byte_i2c (unsigned char device_id, unsigned char first_byte, unsigned char second_byte)

{

  I2CMasterSlaveAddrSet(I2C0_BASE, device_id, false);
    I2CMasterDataPut(I2C0_BASE, first_byte);
    I2CMasterControl(I2C0_BASE, I2C_MASTER_CMD_BURST_SEND_START);
    while(I2CMasterBusy(I2C0_BASE));
    I2CMasterDataPut(I2C0_BASE, second_byte);
    I2CMasterControl(I2C0_BASE, I2C_MASTER_CMD_BURST_SEND_FINISH);
    while(I2CMasterBusy(I2C0_BASE));

}

//*****************************************************************************
// name:
// description: sets the system speed according to the passed in parameter
// param description:
// return value description:
//*****************************************************************************
int set_system_speed (unsigned int how_fast)
{

  switch (how_fast) {
    case INEEDMD_CPU_SPEED_FULL_EXTERNAL:
      //WARNING - do not use on first board rev!!!!
      //turn on the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, INEEDMD_PORTD_XTAL_ENABLE);
      // let it stabalise
      MAP_SysCtlDelay(1000);
      //setting to run on the PLL from the external xtal and switch off the internal oscillator this gives us an 80Mhz clock
      SysCtlClockSet( SYSCTL_SYSDIV_2_5 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ );
      //reset up the i2c bus

      break;
    case INEEDMD_CPU_SPEED_HALF_EXTERNAL:
      //WARNING - do not use on first board rev!!!!
      //turn on the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, INEEDMD_PORTD_XTAL_ENABLE);
      // let it stabalise
      MAP_SysCtlDelay(1000);
      //setting to run on the PLL from the external xtal and switch off the internal oscillator this gives us an 80Mhz clock
      SysCtlClockSet( SYSCTL_SYSDIV_5 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
      //reset up the i2c bus

      break;

    case INEEDMD_CPU_SPEED_QUARTER_EXTERNAL:
      //WARNING - do not use on first board rev!!!!
      //turn on the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, INEEDMD_PORTD_XTAL_ENABLE);
      // let it stabalise
      MAP_SysCtlDelay(1000);
      //setting to run on the PLL from the external xtal and switch off the internal oscillator this gives us an 80Mhz clock
      SysCtlClockSet( SYSCTL_SYSDIV_10 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
      //reset up the i2c bus

      break;

    case INEEDMD_CPU_SPEED_FULL_INTERNAL:
      //setting to run on the PLL from the internal clock and switch off the external xtal pads and pin this gives us an 80 Mhz clock
      SysCtlClockSet( SYSCTL_SYSDIV_2_5 | SYSCTL_USE_PLL | SYSCTL_OSC_INT | SYSCTL_MAIN_OSC_DIS);
      // switch off the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, 0x00);
      break;

    case INEEDMD_CPU_SPEED_HALF_INTERNAL:
      //setting to run on the  the internal OSC and switch off the external xtal pads and pin.. Setting the divider to run us at 40Mhz
      SysCtlClockSet( SYSCTL_SYSDIV_5 | SYSCTL_USE_PLL | SYSCTL_OSC_INT | SYSCTL_MAIN_OSC_DIS);
      // switch off the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, 0x00);
      break;

    case INEEDMD_CPU_SPEED_SLOW_INTERNAL:
      //setting to run on the  the internal OSC and switch off the external xtal pads and pin.. Setting the divider to run us at 500khz
      SysCtlClockSet( SYSCTL_SYSDIV_8 | SYSCTL_USE_OSC | SYSCTL_OSC_INT4 | SYSCTL_MAIN_OSC_DIS);
      // switch off the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, 0x00);
      break;

    case INEEDMD_CPU_SPEED_REALLY_SLOW:
      //setting to run on the  the internal OSC and switch off the external xtal pads and pin.. Setting the divider to run us at 30Khz.
      //Communication is't possible.. we are in hibernation
      SysCtlClockSet( SYSCTL_SYSDIV_1 | SYSCTL_OSC_INT30 | SYSCTL_OSC_INT | SYSCTL_MAIN_OSC_DIS);
      // switch off the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, 0x00);
      break;

    default:
      //setting the intrnal at full speed as the default.
      SysCtlClockSet( SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_INT | SYSCTL_MAIN_OSC_DIS);
      // switch off the external oscillator
      MAP_GPIOPinWrite (GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE, 0x00);
      break;
  }

  return how_fast;


}

void
Set_Timer0_Sleep()
{
    //
    // The Timer0 peripheral must be enabled for use.
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
    //
    // The Timer0 peripheral must be enabled for use.
    //
//    TimerConfigure(TIMER0_BASE, TIMER_CFG_SPLIT_PAIR | TIMER_CFG_B_ONE_SHOT);
    TimerConfigure(TIMER0_BASE, TIMER_CFG_A_ONE_SHOT);
	
}

/******************************************************************************
* name:
* description: services the sys tick interrupt that is proced every ms
* param description:
* return value description:
******************************************************************************/
void vSystick_int_service(void)
{
  bWaveform_timer_tick = true;

  if(bRdio_track_timeout_tick == true)
  {
    uiRdio_timeout_tick++;
  }

  //todo: add other tick variables here
}
/******************************************************************************
* name:
* description:
* param description:
* return value description:
******************************************************************************/
bool bWaveform_did_timer_tick(void)
{
  bool bDid_waveform_timer_tick = false;
  bDid_waveform_timer_tick = bWaveform_timer_tick;

  //todo: disable interrupts
  bWaveform_timer_tick = false;
  //todo: enable interrupts

  return bDid_waveform_timer_tick;
}

void
PowerInitFunction(void)
{
  // set the brown out detection registers

  HWREG(SYSCTL_PBORCTL_R)=SYSCTL_PBORCTL_BOR0;

  // set the LDO in sleep and deep sleep...

  SysCtlLDODeepSleepSet(SYSCTL_LDO_0_90V);
  SysCtlLDOSleepSet(SYSCTL_LDO_0_90V);

  SysCtlDeepSleepPowerSet (SYSCTL_FLASH_LOW_POWER |  SYSCTL_TEMP_LOW_POWER | SYSCTL_SRAM_LOW_POWER );

}

void
GPIOEnable(void)
{
    //
    // Enable Peripheral Clocks 
    // These have to be switched on in order... who knew!
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOC);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

}

void
GPIODisable(void)
{
    //
    // Enable Peripheral Clocks
    // These have to be switched on in order... who knew!
    //
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOA);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOB);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOC);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOD);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOE);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_GPIOF);

}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int
BatMeasureADCEnable(void)
{

    //uint32_t uiData;

    //Enable the ADC Clock
    MAP_SysCtlPeripheralEnable(BATTERY_SYSCTL_PERIPH_ADC);

    MAP_GPIOPinTypeADC(INEEDMD_BATTERY_PORT, INEEDMD_BATTERY_MEASUREMENT_IN_PIN);

//    MAP_SysCtlADCSpeedSet(SYSCTL_ADCSPEED_1MSPS); //(p215 ROM-LM guide)
//    MAP_ADCSequenceDisable(BATTERY_ADC, 3);

//    ROM_ADCSequenceConfigure(BATTERY_ADC, 3, ADC_TRIGGER_PROCESSOR, 0);

    MAP_ADCSequenceDisable(BATTERY_ADC, 3);
    MAP_ADCSequenceConfigure(BATTERY_ADC, 3, ADC_TRIGGER_PROCESSOR, 0);
    MAP_ADCSequenceStepConfigure(BATTERY_ADC, 3, 0, BATTERY_ADC_CTL_CH0 | ADC_CTL_IE | ADC_CTL_END );
    MAP_ADCIntClear(BATTERY_ADC, 3);

    MAP_ADCSequenceEnable(BATTERY_ADC, 3);

    //MAP_ADCSequenceDataGet(BATTERY_ADC, 3, &uiData);


    return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int
BatMeasureADCDisable(void)
{
    while(!SysCtlPeripheralReady(SYSCTL_PERIPH_ADC0));
   //Enable the ADC Clock
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_ADC0);
    //let is stabalise with a majik delay
    return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void
BatMeasureADCRead(void)
{
    //
    // Configuring the SPI port and pins to talk to the analog front end
    // SPI0_BASE is mapped to INEEDMD_ADC_SPI
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI0);
    //no need for a majik delay as we are configuring the GPIO pins as well... and set the pin low to power down the device
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN);
    GPIOPinWrite (GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN, 0x00);

}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
bool
bIs_battery_low(void)
{
  uint8_t uiLow_batt;
  bool bIs_batt_low = false;



  uiLow_batt = GPIOPinRead(GPIO_PORTE_BASE, INEEDMD_RADIO_LOW_BATT_INTERUPT_PIN);

  if(uiLow_batt == INEEDMD_RADIO_LOW_BATT_INTERUPT_PIN)
  {
    bIs_batt_low = true;
  }

  return bIs_batt_low;
}

int
EKGSPIEnable(void)
{
  //
  // Configuring the SPI port and pins to talk to the analog front end
  // SPI0_BASE is mapped to INEEDMD_ADC_SPI
  //
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI0);
  //no need for a majik delay as we are configuring the GPIO pins as well...
  MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN);
  // power UP the ADC
  MAP_GPIOPinWrite(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN);
  // Enable pin PA6 for GPIOOutput
  MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_RESET_OUT_PIN);
  // Enable pin PA0 for GPIOInput
  MAP_GPIOPinTypeGPIOInput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_INTERUPT_PIN);
  // Enable pin PA1 for GPIOOutput
  MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_START_PIN);
  //set the nCS pin as a GPIO
  MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_nCS_PIN);
  // Enable pin PA2 for SSI0 SSI0CLK
  //
  MAP_GPIOPinConfigure(GPIO_PA2_SSI0CLK);
  MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_2);
  //
  // Enable pin PA5 for SSI0 SSI0TX
  //
  MAP_GPIOPinConfigure(GPIO_PA5_SSI0TX);
  MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_5);
  //
  // Enable pin PA3 for SSI0 SSI0FSS
  //
  //MAP_GPIOPinConfigure(GPIO_PA3_SSI0FSS);
  //MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_3);
  //
  // Enable pin PA4 for SSI0 SSI0RX
  //
  MAP_GPIOPinConfigure(GPIO_PA4_SSI0RX);
  MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_4);
  //set SSI for 1MHz clock and 8 bit data, master mode
  SSIConfigSetExpClk(INEEDMD_ADC_SPI, MAP_SysCtlClockGet(), SSI_FRF_MOTO_MODE_2, SSI_MODE_MASTER, 1000000, 8);
  SSIEnable(INEEDMD_ADC_SPI);
//  while(!SysCtlPeripheralReady(INEEDMD_ADC_SPI));


   return 1;

}

int
EKGSPIDisable(void)
{
//  while(!SysCtlPeripheralReady(INEEDMD_ADC_SPI));
  SSIDisable(INEEDMD_ADC_SPI);
  MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_SSI0);
  // power down the ADC
  MAP_GPIOPinWrite(GPIO_PORTA_BASE, INEEDMD_PORTA_ADC_PWRDN_OUT_PIN, 0x00);

  return 1;

}

//*****************************************************************************
// name: RadioUARTEnable
// description: configures and enables the usart for the BT radio
// param description: none
// return value description: none
//*****************************************************************************
int
RadioUARTEnable(void)
{
  ERROR_CODE eEC = ER_FAIL;
  uint32_t uiFlow_control_used = 0;
  //TODO: abstract all the direct references to the processor I/O
  //
  //RADIO_CONFIG
  //
  // Enable the radio UART peripheral
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UART1);
  //configure the radio UART it to operate even if the CPU is in sleep.
  MAP_SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART1);
  //
  // Enable pin PE0 for GPIOOutput - this is the reet for the radio.
  //
  MAP_GPIOPinTypeGPIOOutput(INEEDMD_RADIO_PORT, INEEDMD_RADIO_RESET_PIN);
   //
  // Enable pin PE1 for GPIOInput
  // Not mapping this to an interupt yet as the IC is not yet written
  MAP_GPIOPinTypeGPIOInput(INEEDMD_RADIO_PORT, INEEDMD_RADIO_LOW_BATT_INTERUPT_PIN);
  // Enable pin PE2 for GPIOOutput
  //
  MAP_GPIOPinTypeGPIOOutput(INEEDMD_RADIO_PORT, INEEDMD_RADIO_ENABLE_PIN);

  iRadio_Power_On();
  //
  // Enable pin PF0 for UART1 U1RTS
  // First open the lock and select the bits we want to modify in the GPIO commit register.
  //
  HWREG(INEEDMD_RADIO_SERIAL_PORT + GPIO_O_LOCK) = GPIO_LOCK_KEY;
  HWREG(INEEDMD_RADIO_SERIAL_PORT + GPIO_O_CR) = 0x1;
  //
  // Now modify the configuration of the pins that we unlocked.
  //
  MAP_GPIOPinConfigure(GPIO_PF0_U1RTS);
  MAP_GPIOPinTypeUART(INEEDMD_RADIO_SERIAL_PORT, GPIO_PIN_0);
  //
  // Enable pin PF1 for UART1 U1CTS
  //
  MAP_GPIOPinConfigure(GPIO_PF1_U1CTS);
  MAP_GPIOPinTypeUART(INEEDMD_RADIO_SERIAL_PORT, GPIO_PIN_1);
  //
  // Enable pin PC5 for UART1 U1TX and PC4 for U1RX
  //
  MAP_GPIOPinConfigure(GPIO_PC5_U1TX);
  MAP_GPIOPinConfigure(GPIO_PC4_U1RX);
  //
  // Enable pin PC5 for UART1 U1TX
  //
  MAP_GPIOPinTypeUART(GPIO_PORTC_BASE, GPIO_PIN_5);
  //
  // Enable pin PC4 for UART1 U1RX
  //
  MAP_GPIOPinTypeUART(GPIO_PORTC_BASE, GPIO_PIN_4);

  UARTClockSourceSet(INEEDMD_RADIO_UART, UART_CLOCK_PIOSC);

  //set flow control
  MAP_UARTFlowControlSet(INEEDMD_RADIO_UART, (UART_FLOWCONTROL_TX | UART_FLOWCONTROL_RX));
//  UARTFlowControlSet(INEEDMD_RADIO_UART, (UART_FLOWCONTROL_TX | UART_FLOWCONTROL_RX));
  uiFlow_control_used =  MAP_UARTFlowControlGet(INEEDMD_RADIO_UART);
  if((uiFlow_control_used & (UART_FLOWCONTROL_TX | UART_FLOWCONTROL_RX)) == (UART_FLOWCONTROL_TX | UART_FLOWCONTROL_RX))
  {
    eEC = ER_OK;
  }
  else
  {
    eEC = ER_FAIL;
  }


  if(eEC == ER_OK)
  {
    // Enables the communication FIFO
    MAP_UARTFIFOEnable(INEEDMD_RADIO_UART);

    //configure the UART speed
    MAP_UARTConfigSetExpClk( INEEDMD_RADIO_UART, 16000000, 115200, ( UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE ));

    //finally enable the radio UART
    MAP_UARTEnable(INEEDMD_RADIO_UART);
  }

//    while(!SysCtlPeripheralReady(INEEDMD_RADIO_UART));

    return 1;
}

//*****************************************************************************
// name: iRadioPowerOff
// description: sets the gpio pin to the radio high to turn on the radio
// param description: none
// return value description: 1 if success
//*****************************************************************************
int
iRadio_Power_Off(void)
{
  GPIOPinWrite (GPIO_PORTE_BASE, INEEDMD_RADIO_ENABLE_PIN, 0x00);
  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eSet_radio_to_cmnd_mode(void)
{
  ERROR_CODE eEC = ER_FAIL;

  iRadio_gpio_config(INEEDMD_RADIO_PORT, INEEDMD_RADIO_CMND_PIN);
  MAP_GPIOPinWrite(INEEDMD_RADIO_PORT, INEEDMD_RADIO_CMND_PIN, INEEDMD_RADIO_CMND_PIN);

  return eEC;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eIs_radio_in_cmnd_mode(void)
{
  ERROR_CODE eEC = ER_FAIL;
  uint32_t uiPin_Read = 0;

  uiPin_Read = MAP_GPIOPinRead(INEEDMD_RADIO_PORT, INEEDMD_RADIO_CMND_PIN);

  if((uiPin_Read & INEEDMD_RADIO_CMND_PIN) == INEEDMD_RADIO_CMND_PIN)
  {
    eEC = ER_TRUE;
  }
  else
  {
    eEC = ER_FALSE;
  }

  return eEC;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eSet_radio_to_data_mode(void)
{

}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eIs_radio_in_data_mode(void)
{

}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eUsing_radio_uart_dma(void)
{
  ERROR_CODE eEC = ER_FAIL;

  if(USE_RADIO_UART_DMA == true)
  {
    eEC = ER_TRUE;
  }
  else
  {
    eEC = ER_FALSE;
  }

  return eEC;
}
//*****************************************************************************
// name: iRadioPowerOn
// description: sets the gpio pin to the radio high to turn on the radio
// param description: none
// return value description: 1 if success
//*****************************************************************************
int
iRadio_Power_On(void)
{
  GPIOPinWrite (GPIO_PORTE_BASE, INEEDMD_RADIO_ENABLE_PIN, INEEDMD_RADIO_ENABLE_PIN);
  return 1;
}

//*****************************************************************************
// name: iRadio_interface_enable
// description: enables the serial interface to the external radio interface
// param description: none
// return value description: 1 if success
//*****************************************************************************
int iRadio_interface_enable(void)
{
  ERROR_CODE eEC = ER_OK;
  int iEC = 0;

  RadioUARTEnable();

  //check if UART DMA is enabled
  if(USE_RADIO_UART_DMA == true)
  {
    //configure the radio UART to use DMA
    eEC = Radio_UART_DMA_Config();
  }
  else
  {
    //configure the radio UART interrupts
    iEC = iRadio_interface_int_enable();

    //check the error codes
    if(iEC == 1)
    {
      eEC = ER_OK;
    }
    else
    {
      eEC = ER_FAIL;
    }
  }

  //check the error codes
  if(eEC == ER_OK)
  {
    return 1;
  }
  else
  {
    return -1;
  }
}

int iRadio_gpio_set(uint16_t uiMask)
{
#ifdef DEBUG
  vDEBUG("iRadio_gpio_set() not defined yet SYS HALT");
  while(1){}; //todo: fcn not defined yet
#endif
  return 1;
}

int iRadio_gpio_clear(uint16_t uiMask)
{
#ifdef DEBUG
  vDEBUG("iRadio_gpio_clear() not defined yet SYS HALT");
  while(1){}; //todo: fcn not defined yet
#endif
  return 1;
}

int iRadio_gpio_read(uint16_t uiMask)
{
#ifdef DEBUG
  vDEBUG("iRadio_gpio_read() not defined yet SYS HALT");
  while(1){}; //todo: fcn not defined yet
#endif
  return 1;
}

int iRadio_gpio_config(uint32_t uiRadio_Pin_Port, uint8_t uiPIN_Out_Mask)
{
  MAP_GPIODirModeSet(uiRadio_Pin_Port, uiPIN_Out_Mask, GPIO_DIR_MODE_OUT);

  //todo: read the register and verify settings took hold
  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_send_char(char * byte)
{

  UARTCharPut(INEEDMD_RADIO_UART, *byte);

  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_send_string(char *cSend_string, uint16_t uiBuff_size)
{
  uint32_t i;
  i = strlen(cSend_string);
  if(i != uiBuff_size)
  {
    return 0;
  }

  for (i = 0; i<uiBuff_size; i++)
  {
    UARTCharPut(INEEDMD_RADIO_UART, cSend_string[i]);
  }
  return i;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eRadio_DMA_send_string(char *cSend_string, uint16_t uiBuff_size)
{
#define DEBUG_eRadio_DMA_send_string
#ifdef DEBUG_eRadio_DMA_send_string
  #define  vDEBUG_RDIO_DMA_SNDSTR  vDEBUG
#else
  #define vDEBUG_RDIO_DMA_SNDSTR(a)
#endif
  ERROR_CODE eEC = ER_FAIL;
#if USE_RADIO_UART_DMA == true
  int i = 0;
  tDMA_TX_struct * ptDMA_TX_Send = NULL;
  uint32_t uiModem_status_get = 0;

  //find a free TX buffer
  for(i = 0; i < NUM_DMA_RDIO_TX_BUFFS; i++)
  {
    if(tDMA_TX_struct_array[i].bBuff_free == true)
    {
      //ensure the TX buffer is erased
      memset(&tDMA_TX_struct_array[i].uiTx_Buff, 0x00, DMA_RDIO_TX_BUFFSZ);

      //fill the TX buffer with the data to send
      memcpy(&tDMA_TX_struct_array[i].uiTx_Buff, cSend_string, uiBuff_size);

      //save the buffer size
      tDMA_TX_struct_array[i].uiTx_data_len  = uiBuff_size;

      //save the pointer to the struct to use to send
      ptDMA_TX_Send = &tDMA_TX_struct_array[i];

      tDMA_TX_struct_array[i].bBuff_free = false;

      eEC = ER_OK;
      break;
    }
    else
    {
      //set the error code to no buff available
      eEC = ER_NO_BUFF_AVAILABLE;
    }
  }

  //check if it is ok to start the DMA
  if(eEC == ER_OK)
  {
    // Set up the transfer parameters for the uDMA Radio UART TX channel.  This will
    // configure the transfer source and destination and the transfer size.
    // Basic mode is used because the peripheral is making the uDMA transfer
    // request.  The source is the TX buffer and the destination is the UART
    // data register.
    //
    MAP_UARTModemControlSet(INEEDMD_RADIO_UART, UART_OUTPUT_RTS);

    uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
    while((uiModem_status_get & UART_INPUT_CTS) != UART_INPUT_CTS)
    {
      uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
    }

    MAP_uDMAChannelTransferSet(UDMA_CHANNEL_RADIO_TX | UDMA_PRI_SELECT,
                               UDMA_MODE_AUTO, ptDMA_TX_Send->uiTx_Buff,
                               (void *)(INEEDMD_RADIO_UART + UART_O_DR),
                               ptDMA_TX_Send->uiTx_data_len);

    MAP_uDMAChannelEnable(UDMA_CHANNEL_RADIO_TX);



    bIs_DMA_transmit_in_process = true;
  }
  else if(eEC == ER_NO_BUFF_AVAILABLE)
  {
#ifdef DEBUG
    vDEBUG_RDIO_DMA_SNDSTR("DMA send str SYS HALTED, no buff available to send");
    while(1){};
#endif
  }else{/*nothing*/}
#elif  USE_RADIO_UART_DMA == false
  eEC = ER_NOT_ENABLED;
#endif //USE_RADIO_UART_DMA
  return eEC;
#undef vDEBUG_RDIO_DMA_SNDSTR
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_send_frame(uint8_t *cSend_frame, uint16_t uiFrame_size)
{
  int i;

  for (i = 0; i<uiFrame_size; i++)
  {
    UARTCharPut(INEEDMD_RADIO_UART, cSend_frame[i]);
  }
  return i;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_rcv_string(char *cRcv_string, uint16_t uiBuff_size)
{
  int i;

  for(i = 0; i < uiBuff_size; i++)
  {
    //receive a character from the USART
    cRcv_string[i] = UARTCharGet(INEEDMD_RADIO_UART);

    //check if the end of the radio frame is received
    if(cRcv_string[i] == '\n')
    {
      if(i < 2)
      {
        i = -1;
        continue;
      }
      else
      {
        break;
      }
    }
  }
  return i;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE iRadio_rcv_char(char *cRcv_char)
{
  ERROR_CODE eEC = ER_OK;
  bool bChar_avail = false;

  bChar_avail = UARTCharsAvail(INEEDMD_RADIO_UART);
  if(bChar_avail == false)
  {
    uiRdio_timeout_tick = 0;
    bRdio_track_timeout_tick = true;
    while(bChar_avail == false)
    {
      bChar_avail = UARTCharsAvail(INEEDMD_RADIO_UART);
      if(uiRdio_timeout_tick == 100) //todo: MAGIC Number!
      {
        eEC = ER_TIMEOUT;
        break;
      }
    }
  }
  else
  {
    bRdio_track_timeout_tick = false;
    uiRdio_timeout_tick = 0;
  }

  if(eEC == ER_OK)
  {
    //get the character
    *cRcv_char = UARTCharGetNonBlocking(INEEDMD_RADIO_UART);
  }
  else
  {
    //nothing
  }
  return eEC;
}

//*****************************************************************************
// name: iRadio_rcv_byte
// description: calls the uart char get function.
// param description:
// return value description: returns int error code
//*****************************************************************************
int iRadio_rcv_byte(uint8_t *uiRcv_byte)
{
  *uiRcv_byte = UARTCharGet(INEEDMD_RADIO_UART);
//  *uiRcv_byte = UARTCharGetNonBlocking(INEEDMD_RADIO_UART);

  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eRcv_dma_radio_cmnd_frame(char * cRcv_buff, uint16_t uiMax_buff_size)
{
#define DEBUG_eRcv_dma_radio_cmnd_frame
#ifdef DEBUG_eRcv_dma_radio_cmnd_frame
  #define  vDEBUG_RDIO_DMARCV_CMNDFRAME  vDEBUG
#else
  #define vDEBUG_RDIO_DMARCV_CMNDFRAME(a)
#endif
  ERROR_CODE eEC = ER_FAIL;
#if USE_RADIO_UART_DMA == true
  int index = 0;
  int iCpy_index = 0;
  tDMA_RX_struct * ptDMA_que_buff = NULL;
  tDMA_RX_struct * ptDMA_curr_fill_buff = NULL;
  bool bIs_DMA_chan_en = false;
  bool bWhile_char_avail = false;
  uint32_t uiModem_status_get = 0;
  char * cEnd_of_frame = NULL;

  while(bIs_DMA_transmit_in_process == true)
  {
    //we wait
  }
//  while(MAP_UARTBusy(INEEDMD_RADIO_UART) == true)
//  {
//    //we wait
//  }

//  uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
//  while((uiModem_status_get & UART_INPUT_CTS) != UART_INPUT_CTS)
//  {
//    uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
//  }
//  vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv, CTS rdio done sending");

//  bWhile_char_avail = MAP_UARTCharsAvail(INEEDMD_RADIO_UART);
//  while(bWhile_char_avail == true)
//  {
//    bWhile_char_avail = MAP_UARTCharsAvail(INEEDMD_RADIO_UART);
//  }
//
//  bIs_DMA_chan_en = MAP_uDMAChannelIsEnabled(UDMA_CHANNEL_RADIO_RX);
//  if(bIs_DMA_chan_en == true)
//  {
//    MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_RX);
//  }else{/*nothing*/}

  eGet_curr_DMA_fill_buff(&ptDMA_curr_fill_buff);

  cEnd_of_frame = strstr((char *)ptDMA_curr_fill_buff->uiRcv_Buff, "\r\n");
  while(cEnd_of_frame == NULL)
  {
    cEnd_of_frame = strstr((char *)ptDMA_curr_fill_buff->uiRcv_Buff, "\r\n");
  }

  //todo: edit this comment once a better understanding of the CTS isr is understood
  //service the DMA rcv buffers since the CTS isr isn't firing
  vRadio_interface_DMA_rcv_service();

  //cycle through the buffers and find the one that was filled
  for(index = 0; index < NUM_DMA_RDIO_RCV_BUFFS; index++)
  {
    ptDMA_que_buff = &tDMA_RX_struct_array[index];

    //check if the buffer is NOT free, therefore filled with data
    if(ptDMA_que_buff->bBuff_free == false)
    {
      //check if the buffer was queued for an app to review
      if(ptDMA_que_buff->eApp_Buff_Dest == RB_IWRAP_CMND)
      {
        iNum_cmnd_buffs++;
        if(iNum_cmnd_buffs == 1)                             //todo: debug delete
        {                                                    //
//          MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_RX);   //
          iNum_cmnd_buffs = 1;                               //
        }                                                    //
        //preset error code to ok for copy status
        eEC = ER_OK;
        for(iCpy_index = 0; iCpy_index < uiMax_buff_size; iCpy_index++)
        {
          //check if the transfer to buffer was overfilled
          if(iCpy_index >= uiMax_buff_size)
          {
            eEC = ER_OVERWRITE;
            break;
          }

          //copy the receive byte to the transfer buffer
          if(eEC == ER_OK)
          {
            cRcv_buff[iCpy_index] = ptDMA_que_buff->uiRcv_Buff[iCpy_index];
          }

          //Check if the end of the received frame was reached
          if(cRcv_buff[iCpy_index] == 0x00)
          {
            eEC = ER_DONE;
            //free and empty the buffer
            vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv, cpy done & buff freed");
            ptDMA_que_buff->eApp_Buff_Dest = RB_NONE;
            ptDMA_que_buff->bBuff_free = true;
            ptDMA_que_buff->uiRcv_data_len   = 0;
            memset(ptDMA_que_buff->uiRcv_Buff, 0x00, DMA_RDIO_RCV_BUFFSZ);
            break;
          }
        }

        //check fatal errors
        if(eEC == ER_OVERWRITE)
        {
#ifdef DEBUG
          vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv SYS HALTED, cpy overwrite");
          while(1){};
#endif
        }
        else if(eEC == ER_FAIL)
        {
#ifdef DEBUG
          vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv SYS HALTED, undefined error state");
          while(1){};
#endif
        }else{/*nothing*/}
      }else{/*nothing*/}
    }else{/*nothing*/}

    //check the error codes
    if(eEC == ER_DONE)
    {
      //buffer transfer was complete
      eEC = ER_OK;
      break;
    }else{/*nothing*/}
  }

  //check if all receive buffers were checked and no data was copied
  if(index == NUM_DMA_RDIO_RCV_BUFFS)
  {
    if(eEC == ER_FAIL)
    {
      //no data was received
      eEC = ER_NODATA;
    }else{/*nothing*/}
#ifdef DEBUG
    vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv SYS HALTED, no data rcvd");
    while(1){};
#endif
  }else{/*nothing*/}

#elif  USE_RADIO_UART_DMA == false
  eEC = ER_NOT_ENABLED;
#ifdef DEBUG
  vDEBUG_RDIO_DMARCV_CMNDFRAME("Cmnd rcv SYS HALTED, DMA not used fcn should not be called");
  while(1){};
#endif
#endif //USE_RADIO_UART_DMA

  return eEC;
#undef vDEBUG_RDIO_DMARCV_CMNDFRAME
}

//todo: eRcv_dma_radio_boot_frame may not be needed
//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eRcv_dma_radio_boot_frame(char * cRcv_buff, uint16_t uiMax_buff_size)
{
#define DEBUG_eRcv_dma_radio_boot_frame
#ifdef DEBUG_eRcv_dma_radio_boot_frame
  #define  vDEBUG_DMARCV_BOOTFRM  vDEBUG
#else
  #define vDEBUG_DMARCV_BOOTFRM(a)
#endif
  ERROR_CODE eEC = ER_FAIL;
#if USE_RADIO_UART_DMA == true
  int index = 0;
  int iCpy_index = 0;
  tDMA_RX_struct * ptDMA_que_buff = NULL;
  bool bIs_DMA_chan_en = false;
  uint32_t uiModem_status_get = 0;

  while(bIs_DMA_transmit_in_process == true)
  {
    //we wait
  }
  while(MAP_UARTBusy(INEEDMD_RADIO_UART) == true)
  {
    //we wait
  }

  uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
  while((uiModem_status_get & UART_INPUT_CTS) != UART_INPUT_CTS)
  {
    uiModem_status_get = MAP_UARTModemStatusGet(INEEDMD_RADIO_UART);
  }
  vDEBUG_DMARCV_BOOTFRM("Boot rcv, CTS rdio done sending");

  bIs_DMA_chan_en = MAP_uDMAChannelIsEnabled(UDMA_CHANNEL_RADIO_RX);
  if(bIs_DMA_chan_en == true)
  {
    MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_RX);
  }else{/*nothing*/}

  //cycle through the buffers and find the one that was filled
  for(index = 0; index < NUM_DMA_RDIO_RCV_BUFFS; index++)
  {
    ptDMA_que_buff = &tDMA_RX_struct_array[index];

    //check if the buffer is NOT free, therefore filled with data
    if(ptDMA_que_buff->bBuff_free == false)
    {
      //check if the buffer was queued for an app to review
      if(ptDMA_que_buff->eApp_Buff_Dest == RB_IWRAP_CMND)
      {
        iNum_cmnd_buffs++;
        if(iNum_cmnd_buffs == 1)                             //todo: debug delete
        {                                                    //
//          MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_RX);   //
          iNum_cmnd_buffs = 1;                               //
        }                                                    //
        //preset error code to ok for copy status
        eEC = ER_OK;
        for(iCpy_index = 0; iCpy_index < uiMax_buff_size; iCpy_index++)
        {
          //check if the transfer to buffer was overfilled
          if(iCpy_index >= uiMax_buff_size)
          {
            eEC = ER_OVERWRITE;
            break;
          }

          //copy the receive byte to the transfer buffer
          if(eEC == ER_OK)
          {
            cRcv_buff[iCpy_index] = ptDMA_que_buff->uiRcv_Buff[iCpy_index];
          }

          //Check if the end of the received frame was reached
          if(cRcv_buff[iCpy_index] == 0x00)
          {
            eEC = ER_DONE;
            //free and empty the buffer
            vDEBUG_DMARCV_BOOTFRM("Boot rcv, cpy done & buff freed");
            ptDMA_que_buff->eApp_Buff_Dest = RB_NONE;
            ptDMA_que_buff->bBuff_free = true;
            ptDMA_que_buff->uiRcv_data_len   = 0;
            memset(ptDMA_que_buff->uiRcv_Buff, 0x00, DMA_RDIO_RCV_BUFFSZ);
            break;
          }
        }

        //check fatal errors
        if(eEC == ER_OVERWRITE)
        {
#ifdef DEBUG
          vDEBUG_DMARCV_BOOTFRM("Boot rcv SYS HALTED, cpy overwrite");
          while(1){};
#endif
        }
        else if(eEC == ER_FAIL)
        {
#ifdef DEBUG
          vDEBUG_DMARCV_BOOTFRM("Boot rcv SYS HALTED, undefined error state");
          while(1){};
#endif
        }else{/*nothing*/}
      }else{/*nothing*/}
    }else{/*nothing*/}

    //check the error codes
    if(eEC == ER_DONE)
    {
      //buffer transfer was complete
      eEC = ER_OK;
      break;
    }else{/*nothing*/}
  }

  //check if all receive buffers were checked and no data was copied
  if(index == NUM_DMA_RDIO_RCV_BUFFS)
  {
    if(eEC == ER_FAIL)
    {
      //no data was received
      eEC = ER_NODATA;
    }else{/*nothing*/}
#ifdef DEBUG
    vDEBUG_DMARCV_BOOTFRM("Boot rcv SYS HALTED, no data rcvd");
    while(1){};
#endif
  }else{/*nothing*/}

#elif  USE_RADIO_UART_DMA == false
  eEC = ER_NOT_ENABLED;
#ifdef DEBUG
  vDEBUG_DMARCV_BOOTFRM("Boot rcv SYS HALTED, DMA not used fcn should not be called");
  while(1){};
#endif
#endif //USE_RADIO_UART_DMA

  return eEC;
#undef vDEBUG_DMARCV_BOOTFRM
}

ERROR_CODE eIs_UART_using_DMA(void)
{
  if(USE_RADIO_UART_DMA == true)
  {
    return ER_TRUE;
  }
  else
  {
    return ER_FALSE;
  }
}
//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_interface_int_enable(void)
{
  uint32_t ui32Status;

  // Get the interrrupt status.
  ui32Status = MAP_UARTIntStatus(INEEDMD_RADIO_UART, true);
  //clear any asserted interrupts
  MAP_UARTIntClear(INEEDMD_RADIO_UART, ui32Status);

  //disable the uart interrupt first
  iRadio_interface_int_disable();

  //
  // Enable the UART interrupt.
  //
  ROM_IntEnable(INEEDMD_RADIO_UART_INT);
  ROM_UARTIntEnable(INEEDMD_RADIO_UART, UART_INT_TX | UART_INT_RX | UART_INT_RT | UART_INT_CTS);

  eMaster_int_enable();
  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
int iRadio_interface_int_disable(void)
{
  //
  // Disable the radio uart interrupt.
  //
  ROM_IntDisable(INEEDMD_RADIO_UART_INT);
  ROM_UARTIntDisable(INEEDMD_RADIO_UART, UART_INT_TX | UART_INT_RX | UART_INT_RT | UART_INT_CTS);
  return 1;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vRadio_interface_int_service(uint16_t uiInt_id)
{
//  char cRcv_string[256];
//  memset(cRcv_string, 0x00, 256);

  if(uiInt_id == UART_INT_RX)
  {
    bIs_usart_data = true;

//    iRadio_rcv_string(cRcv_string, 256);
  }
  else if(uiInt_id == UART_INT_CTS)  //CTS interrupt id, signalling data was received
  {
    //check if the radio uart is using DMA
    if(bIs_Radio_UART_using_dma == true)
    {
      iNum_cts_procs++;
      //service the DMA receive
      vRadio_interface_DMA_rcv_service();
    }
    //else just set the usart data control variable
    else
    {
      bIs_uart_done = true;
    }
  }
  else{/* do nothing */}
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vRadio_interface_DMA_int_service(uint32_t ui32DMA_int_status)
{
  int i = 0;
  if((ui32DMA_int_status & RADIO_TX_UDMA_CHANNEL_BITMASK) == RADIO_TX_UDMA_CHANNEL_BITMASK)
  {
    bIs_DMA_transmit_in_process = false;
//    MAP_UARTModemControlClear(INEEDMD_RADIO_UART, UART_OUTPUT_RTS);
//    MAP_uDMAChannelDisable(UDMA_CHANNEL_RADIO_TX);
//    vRadio_interface_DMA_tx_service();
  }

  if((ui32DMA_int_status & RADIO_RX_UDMA_CHANNEL_BITMASK) == RADIO_RX_UDMA_CHANNEL_BITMASK)
  {
    i++;
  }
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vRadio_interface_int_service_timeout(uint16_t uiInt_id)
{
  if((uiInt_id & UART_INT_RT) == UART_INT_RT)
  {
    bIs_usart_timeout = true;

//    iRadio_rcv_string(cRcv_string, 256);
  }
  else
  {
    bIs_usart_timeout = false;
  }
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
bool bRadio_is_data(void)
{
  //todo: disable interrupts
  bool bWas_usart_data = bIs_usart_data;

  bIs_usart_data = false;
//todo: enable interrupts
  return bWas_usart_data;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
bool bGet_CTS_Status(void)
{
  //todo: disable interrupts
  bool bWas_CTS_flagged = bIs_uart_done;

  bIs_uart_done = false;
//todo: enable interrupts
  return bWas_CTS_flagged;
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void
SDCardSPIInit(void)
{
  //
  //SPI 1 is used for the FLASH
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI1);
  //
  // Enable pin PD2 for SSI1 SSI1RX
  //
  MAP_GPIOPinConfigure(GPIO_PD2_SSI1RX);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_2);
  //
  // Enable pin PD3 for SSI1 SSI1TX
  //
  MAP_GPIOPinConfigure(GPIO_PD3_SSI1TX);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_3);
  //
  // Enable pin PD0 for SSI1 SSI1CLK
  //
  MAP_GPIOPinConfigure(GPIO_PD0_SSI1CLK);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_0);
  //
  // Enable pin PD1 for SSI1 SSI1FSS
  //
  MAP_GPIOPinConfigure(GPIO_PD1_SSI1FSS);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_1);
  SSIEnable(INEEDMD_FLASH_SPI);
  SSIConfigSetExpClk(INEEDMD_FLASH_SPI, MAP_SysCtlClockGet(), SSI_FRF_MOTO_MODE_2, SSI_MODE_MASTER, 1000000, 8);
  SSIEnable(INEEDMD_FLASH_SPI);
  //  while(!SysCtlPeripheralReady(INEEDMD_FLASH_SPI));

  //
  //SPI 1 is used for the FLASH
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI1);
  //
  // Enable pin PD2 for SSI1 SSI1RX
  //
  MAP_GPIOPinConfigure(GPIO_PD2_SSI1RX);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_2);
  //
  // Enable pin PD3 for SSI1 SSI1TX
  //
  MAP_GPIOPinConfigure(GPIO_PD3_SSI1TX);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_3);
  //
  // Enable pin PD0 for SSI1 SSI1CLK
  //
  MAP_GPIOPinConfigure(GPIO_PD0_SSI1CLK);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_0);
  //
  // Enable pin PD1 for SSI1 SSI1FSS
  //
  MAP_GPIOPinConfigure(GPIO_PD1_SSI1FSS);
  MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_1);
  SSIEnable(INEEDMD_FLASH_SPI);
  SSIConfigSetExpClk(INEEDMD_FLASH_SPI, MAP_SysCtlClockGet(), SSI_FRF_MOTO_MODE_2, SSI_MODE_MASTER, 1000000, 8);
  SSIEnable(INEEDMD_FLASH_SPI);
  //  while(!SysCtlPeripheralReady(INEEDMD_FLASH_SPI));


}

void
SDCardSPIDisable(void)
{
  //  while(!SysCtlPeripheralReady(INEEDMD_FLASH_SPI));
  SSIDisable(INEEDMD_FLASH_SPI);
    //
    //SPI 1 is used for the FLASH
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_SSI1);

}

void
LEDI2CEnable(void)
{
  //
  // Enable pin PB2 for I2C0 I2C0SCL
  //
  MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_I2C0);
  // majik delay as there are things that need to settle.  Because the I2C is very low speed block this is twice as long as the other delays
  MAP_SysCtlDelay(200);
  //
  // I2C Clk is on portB pin 2
  //
  MAP_GPIOPinTypeI2CSCL(GPIO_PORTB_BASE, GPIO_PIN_2);
  MAP_GPIOPinConfigure(GPIO_PB2_I2C0SCL);
  //
  // I2C SDA is on portB pin 3
  //
  MAP_GPIOPinTypeI2C(GPIO_PORTB_BASE, GPIO_PIN_3);
  MAP_GPIOPinConfigure(GPIO_PB3_I2C0SDA);
    I2CMasterInitExpClk(INEEDMD_LED_I2C, MAP_SysCtlClockGet(), true);
  I2CMasterEnable(INEEDMD_LED_I2C);
    //  while(!SysCtlPeripheralReady(INEEDMD_LED_I2C));

}

void
LEDI2CDisable(void)
{
    //  while(!SysCtlPeripheralReady(SYSCTL_PERIPH_I2C0));
    I2CMasterDisable(INEEDMD_LED_I2C);
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_I2C0);

}

void
XTALControlPin(void)
{
    //
    // set up the crystal control pin...
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE, INEEDMD_PORTD_XTAL_ENABLE);
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void
USBPortEnable(void)
{
    // USB block need the processor at full speed to complete the initiaisation.
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_USB0);
    //
    // Enable pin PD4 for USB0 USB0DM
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTD_BASE, GPIO_PIN_4);
    //
    // Enable pin PD5 for USB0 USB0DP
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTD_BASE, GPIO_PIN_5);

#define SYSTICKS_PER_SECOND 100
    ROM_FPULazyStackingEnable();
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTD_BASE, GPIO_PIN_5 | GPIO_PIN_4);

    set_system_speed(INEEDMD_CPU_SPEED_HALF_EXTERNAL);

    uint32_t ui32SysClock = MAP_SysCtlClockGet();
//    MAP_SysTickPeriodSet(MAP_SysCtlClockGet() / SYSTICKS_PER_SECOND);
//    MAP_SysTickIntEnable();
//    MAP_SysTickEnable();
//    eMaster_int_disable();
//    MAP_SysTickIntDisable();
//    MAP_SysTickDisable();
    HWREG(NVIC_DIS0) = 0xffffffff;
    HWREG(NVIC_DIS1) = 0xffffffff;
    // 1. Enable USB PLL
    // 2. Enable USB controller
//    ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_USB0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_USB0);
//    ROM_SysCtlPeripheralReset(SYSCTL_PERIPH_USB0);
    MAP_SysCtlPeripheralReset(SYSCTL_PERIPH_USB0);
    MAP_SysCtlUSBPLLEnable();
    // 3. Enable USB D+ D- pins
    // 4. Activate USB DFU
    MAP_SysCtlDelay(ui32SysClock / 3);
    eMaster_int_enable(); // Re-enable interrupts at NVIC level

    //  while(!SysCtlPeripheralReady(SYSCTL_PERIPH_USB0));

//    ROM_USBIntEnableControl(USB0_BASE,(USB_INTCTRL_DISCONNECT | USB_INTCTRL_CONNECT));
    MAP_USBIntEnableControl(USB0_BASE, USB_INTCTRL_DISCONNECT |
                                       USB_INTCTRL_CONNECT);
//    MAP_USBIntEnableEndpoint(USB0_BASE, USB_INTEP_ALL);

    MAP_USBDevConnect(USB0_BASE);

    MAP_IntEnable(INT_USB0);

}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void
USBPortDisable(void)
{

    uint32_t ui32SysClock = MAP_SysCtlClockGet();

    //disable all interrupts
    eMaster_int_disable();

    //disable the USB0 interrupt
    ROM_IntDisable(INT_USB0);

    //disconnect the USB0 device
    MAP_USBDevDisconnect(USB0_BASE);

    //disable the interrupt controll
    MAP_USBIntDisableControl(USB0_BASE, USB_INTCTRL_DISCONNECT |
                                        USB_INTCTRL_CONNECT);

    //turn off the USB PLL
    MAP_SysCtlUSBPLLDisable();

    //do a short delay
    MAP_SysCtlDelay(ui32SysClock / 3);

    // disable the entier USB0 peripheral
    MAP_SysCtlPeripheralDisable(SYSCTL_PERIPH_USB0);

    set_system_speed(INEEDMD_CPU_SPEED_HALF_INTERNAL);

    //re-enable all interrupts
    eMaster_int_enable();
}

//*****************************************************************************
// name:
// description:
// param description:
// return value description:
//*****************************************************************************
void vUSBServiceInt(uint32_t uiUSB_int_flags)
{

  if((uiUSB_int_flags & USB_INTCTRL_SOF) == USB_INTCTRL_SOF)
  {
      bIs_USB_sof = true;
  }
}

bool bIs_usb_physical_data_conn(void)
{
  bool bWas_physical_data_conn;

  eMaster_int_disable();

  bWas_physical_data_conn = bIs_USB_sof;
  bIs_USB_sof = false;

  //re-enable interrupts
  eMaster_int_enable();

  return bWas_physical_data_conn;
}

/*
* ConfigureSleepleep(void)
*
*This function sets up the behaviour of the cpu peripherals in sleep mode
*
*/

void ConfigureSleep(void)
{
        //
        // Which peripherals are enabled in sleep
        // Peripherals should be enabled OR disabled
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_ADC0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_ADC0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_ADC1);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_ADC1);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_CAN0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_CAN0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_COMP0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_COMP0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOA);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOA);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOB);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOB);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOC);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOC);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOD);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOD);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOE);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOE);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_GPIOF);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_GPIOF);
        //
        SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_HIBERNATE);
        //SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_HIBERNATE);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_I2C0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_I2C0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_I2C1);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_I2C1);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_I2C2);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_I2C2);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_I2C3);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_I2C3);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_I2C4);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_I2C4);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_EEPROM0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_EEPROM0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_SSI0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_SSI0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_SSI1);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_SSI1);
        //
        SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER0);
        //SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER1);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER1);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER2);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER2);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER3);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER3);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER4);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER4);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_TIMER5);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_TIMER5);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART0);
        //
        SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART1);
        //SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART1);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART2);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART2);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART3);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART3);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART4);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART4);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART5);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART5);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART6);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART6);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UART7);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UART7);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_UDMA);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_UDMA);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_USB0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_USB0);
        //
        //SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_WDOG0);
        SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_WDOG0);
        //
        SysCtlPeripheralSleepEnable(SYSCTL_PERIPH_WDOG1);
        //SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_WDOG1);
        //
}

void ConfigureDeepSleep(void)
{
	//
	// Which peripherals are enabled in sleep
	// Peripherals should be enabled OR disabled
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_ADC0);
	SysCtlPeripheralSleepDisable(SYSCTL_PERIPH_ADC0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_ADC1);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_ADC1);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_CAN0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_CAN0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_COMP0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_COMP0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOA);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOA);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOB);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOB);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOC);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOC);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOD);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOD);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOE);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOE);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_GPIOF);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_GPIOF);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_HIBERNATE);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_HIBERNATE);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_I2C0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_I2C0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_I2C1);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_I2C1);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_I2C2);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_I2C2);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_I2C3);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_I2C3);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_I2C4);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_I2C4);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_EEPROM0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_EEPROM0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_SSI0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_SSI0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_SSI1);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_SSI1);
	//
	SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER0);
	//SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER1);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER1);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER2);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER2);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER3);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER3);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER4);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER4);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_TIMER5);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_TIMER5);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART1);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART1);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART2);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART2);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART3);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART3);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART4);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART4);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART5);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART5);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART6);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART6);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UART7);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UART7);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_UDMA);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_UDMA);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_USB0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_USB0);
	//
	//SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_WDOG0);
	SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_WDOG0);
	//
	SysCtlPeripheralDeepSleepEnable(SYSCTL_PERIPH_WDOG1);
	//SysCtlPeripheralDeepSleepDisable(SYSCTL_PERIPH_WDOG1);
	//
}

//*****************************************************************************
// name: eMaster_int_enable
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eMaster_int_enable(void)
{
  ERROR_CODE eEC = ER_OK;
  MAP_IntMasterEnable();
  return eEC;
}

//*****************************************************************************
// name: eMaster_int_disable
// description:
// param description:
// return value description:
//*****************************************************************************
ERROR_CODE eMaster_int_disable(void)
{
  ERROR_CODE eEC = ER_OK;
  MAP_IntMasterDisable();
  return eEC;
}

//*****************************************************************************
// name: iHW_delay
// description: performs a blocking hardware based delay. the delay is in 100ms
//  "chunks"
// param description:  uint32_t number of 1ms cycles to delay
// return value description: the number of cycles delayed
//*****************************************************************************
int
iHW_delay(uint32_t uiDelay)
{
  int i;
  for(i = 0; i < uiDelay; i++)
  {
//    MAP_SysCtlDelay( MAP_SysCtlClockGet() / 30  );
    MAP_SysCtlDelay(uiSys_clock_rate_ms);
  }
  return i;
}

//
//a processor loop wait timer.  The number of cycles are calculated from the frequency of the main clock.
//
//void vHW_delay (unsigned int tenths_of_seconds)
//{
//  MAP_SysCtlDelay(( MAP_SysCtlClockGet() / 30  )*tenths_of_seconds );
//}

//*****************************************************************************
// name: iBoard_init
// description: calls the low level board driver initalization functions
// param description: none
// return value description: 1 if success
//*****************************************************************************
int
iBoard_init(void)
{

  uint32_t uiSys_clock_rate;

  //Set up a colock to 40Mhz off the PLL.  This is fat enough to allow for things to set up well, but not too fast that we have big temporal problems.
  SysCtlClockSet( SYSCTL_SYSDIV_5 | SYSCTL_USE_PLL | SYSCTL_OSC_INT | SYSCTL_MAIN_OSC_DIS);

  uiSys_clock_rate_ms = MAP_SysCtlClockGet() /3000;

  // set the brown out interupt and power down voltage
  PowerInitFunction();

  // switch on the GPIO
  GPIOEnable();

  //start the SPI bus to the capture ADC
  EKGSPIEnable();

  //start the radio UART
  RadioUARTEnable();

  //and the ASC enable to measure the battery
  BatMeasureADCEnable();

  //start the LED driver so that we can flash and dance
  LEDI2CEnable();

  //start the pin that allows us to shut down the external oscillator... savng some power
  XTALControlPin();

  //setup the USB port.  This can't be used in this clock mode.
  USBPortEnable();

  MAP_SysTickEnable();
  uiSys_clock_rate = MAP_SysCtlClockGet();

  uiSys_clock_rate = uiSys_clock_rate/40000;

  MAP_SysTickPeriodSet(uiSys_clock_rate);

  MAP_SysTickIntEnable();

  eMaster_int_enable();
  return 1;
}
#endif //__BOARD_C__
